apiVersion: apps/v1
kind: Deployment
metadata:
  name: mangos-deployment
  namespace: mangos
  labels:
    app: mangos-server
spec:
  selector:
    matchLabels:
      app: mangos-server
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mangos-server
    spec:
      containers:
      - env:
        - name: DATABASE_HOSTNAME
          value: mangos-mysql
        - name: MYSQL_APP_PASSWORD
          value: mangos
        - name: MYSQL_APP_USER
          value: mangos
        - name: SERVERIP
          value: mangos-mysql
        - name: STARTLEVEL
          value: "60"
        - name: MONEY
          value: "100000000"
        - name: SKIPCIN
          value: "1"
        image: filipdadgar/mangos-classic
        name: mangos-deployment
        ports:
        - containerPort: 8085
        - containerPort: 3724
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /var/log/wow
          name: wow-vanilla-log-data
#        - mountPath: /cmangos/etc/
#          name: config
        - mountPath: /cmangos/bin/dbc
          name: wow-vanilla-server-dbc
        - mountPath: /cmangos/bin/maps
          name: wow-vanilla-server-maps
        - mountPath: /cmangos/bin/mmaps
          name: wow-vanilla-server-mmaps
        - mountPath: /cmangos/bin/vmaps
          name: wow-vanilla-server-vmaps
        - mountPath: /etc/ahbot.conf
          name: ahbot
      restartPolicy: Always
      volumes:
      - name: wow-vanilla-log-data
        hostPath: 
          path: /media/download/kubeconfig/mangos/log
#      - name: config
#        hostPath:
#          path: /media/download/kubeconfig/mangos/config/
      - name: wow-vanilla-server-dbc
        hostPath:
          path: /media/download/kubeconfig/mangos/5875/dbc
      - name: wow-vanilla-server-maps
        hostPath:
          path: /media/download/kubeconfig/mangos/maps
      - name: wow-vanilla-server-mmaps
        hostPath: 
          path: /media/download/kubeconfig/mangos/mmaps
      - name: wow-vanilla-server-vmaps
        hostPath:
          path: /media/download/kubeconfig/mangos/vmaps
      - name: ahbot
        hostPath:
          path: /media/download/kubeconfig/mangos/config/ahbot.conf
status: {}

